networks:
  app_network:  # Define a custom network

services:
  postgres:
    image: postgres:15.5
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network  # Attach to the custom network

  web:
    build: .
    image: test-ruby:v5
    container_name: rails_app
    volumes:
      - .:/app
    ports:
      - "7000:80"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postres:5432/${POSTGRES_DB}
      MESSAGE_PROCESSOR_SQS_QUEUE: "test"
      START_PROMETHEUS: false
      SECRET_KEY_BASE: prod
    depends_on:
      - postgres
    networks:
      - app_network  # Attach to the custom network

volumes:
  postgres_data:
  app: